name: Build

on:
  push:
    branches: [ master ]
    paths: [ Dockerfile, entrypoint-wrapper.sh ]
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push images
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ github.repository_owner }}/github-actions-runner:latest
